version: '3.8'

services:
  target-server:
    build: ./target-server
    container_name: SIMIR_TARGET
    networks:
      simir-net:
        ipv4_address: 172.18.0.2
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo

networks:
  simir-net:
    external: true
    name: simir-net
